### ISSUE TITLE
uninitialized constant Ezid::BatchDownload::DateTime

### ISSUE THREAD

**Issue by dunn** [duke-libraries/ezid-client#67]
On Mac OS 10.11.3, Ruby 2.3.0, I get a `NameError` using this script:
```ruby
# batch_arks.rb
require "ezid-client"

Ezid::Client.configure do |config|
  config.user = "****"
  config.password = "****"
end

batch = Ezid::BatchDownload.new(:csv)
batch.column = %w[_id _target]
batch.type = :ark

dl = batch.download_url
puts dl
```
The output:
```
$ ruby batch_arks.rb
/usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/batch_download.rb:62:in `<class:BatchDownload>': uninitialized constant Ezid::BatchDownload::DateTime (NameError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/batch_download.rb:8:in `<module:Ezid>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/batch_download.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/client.rb:9:in `require_relative'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/client.rb:9:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid-client.rb:1:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from batch_arks.rb:1:in `<main>'
```

**Comment by dunn** [comment]
Actually I get this error just when running `require 'ezid-client'` in the IRB:
```
🔥  irb
irb(main):001:0> require 'ezid-client'
NameError: uninitialized constant Ezid::BatchDownload::DateTime
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/batch_download.rb:62:in `<class:BatchDownload>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/batch_download.rb:8:in `<module:Ezid>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/batch_download.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/client.rb:9:in `require_relative'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid/client.rb:9:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/gems/2.3.0/gems/ezid-client-1.4.2/lib/ezid-client.rb:1:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from (irb):1
        from /usr/local/bin/irb:11:in `<main>'

**Comment by dchandekstark** [comment]
Fixed in d64279b41dc3b2150ad7cf0c173b6e1ab0465325 (commit message incorrectly refs #12).  To be included in v1.4.3.

**Comment by dchandekstark** [comment]
@dunn Thanks for reporting!

**Comment by dunn** [comment]
No problem, thanks for the fix!
