### ISSUE TITLE
Error during service outage

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/ezid-client#88]
```
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/responses/identifier_response.rb:9:in `id'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:356:in `mint'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:351:in `create_or_mint'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:364:in `persist'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:174:in `save'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:58:in `block in mint'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:129:in `initialize'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:56:in `new'
/usr/local/bundle/gems/ezid-client-1.8.0/lib/ezid/identifier.rb:56:in `mint'
```

**Comment by dchandekstark** [comment]
I think this is resolved in v1.9.0.
